version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: dollar-tool-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=False
      - PYTHONPATH=/app
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - dollar-tool-network

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: dollar-tool-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dollar-tool-network

networks:
  dollar-tool-network:
    driver: bridge

volumes:
  logs:
    driver: local
